# Generated by Django 4.2.5 on 2023-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='reactions',
            field=models.ManyToManyField(blank=True, to='publications.reaction'),
        ),
    ]
