# Generated by Django 4.2.5 on 2023-10-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_reactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tipo',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='publicacion',
            new_name='publication',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='tipo',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='publication',
            name='reactions',
            field=models.ManyToManyField(blank=True, related_name='publications_reacted', to='publications.reaction'),
        ),
    ]
