# Generated by Django 4.2.5 on 2023-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_alter_comment_options_alter_publication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='gif',
            field=models.URLField(blank=True, null=True),
        ),
    ]
